import React, { ReactElement } from "react";
import { keywordsList } from "costants/staticContent";
import Image from "next/image";

import CheckIcon from "@mui/icons-material/Check";

import Grid from "@mui/material/Grid";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Typography from "@mui/material/Typography";

const KeywordsContent = (): ReactElement => {
  return (
    <Grid container spacing={8}>
      <Grid
        item
        xs={12}
        sm={6}
        p={8}
        sx={{
          display: "flex",
          alignItems: "center",
          flexDirection: "column"
        }}>
        <Typography variant="h6" mb={6}>
          1024 Unique Keywords
        </Typography>
        <Image src="/images/banner.png" width={400} height={400} />
      </Grid>
      <Grid item xs={12} sm={6} p={8}>
        <Typography variant="subtitle2">
          Each keyword is unique by definition, and its NFT is generated by a
          custom program with a randomly selected style (effects, font, colors,
          background, ...). They are all cool.
        </Typography>
        <List>
          {keywordsList.map((keyword, ind) => (
            <ListItem key={`keyword-${ind}`}>
              <ListItemIcon>
                <CheckIcon color="success" />
              </ListItemIcon>
              <ListItemText primary={keyword} />
            </ListItem>
          ))}
        </List>
      </Grid>
    </Grid>
  );
};

export default KeywordsContent;
