export const keywordsList: string[] = [
  "Each keyword is unique by definition, and its NFT is generated by a custom program with a randomly selected style (effects, font, colors, background, ...). They are all cool.",
  "Keywords are minted on Ethereum as ERC-721 tokens, only on this website.",
  "Many utility benefits, that go beyond the beauty of the image.",
  "After minting, keywords can be traded on the secondary markets.",
  "The owner has all commercial rights for his NFT image.",
  "Blind minting and later reveal. Get your random keyword(s), and exchange them later if you want a specific language."
];

export const tokenUtilitiesList: string[] = [
  "Access to all the source code for this minting website, the Smart Contract, the custom tools to generate the random images and metadata, and more utilities.",
  " All keywords displayed on the Ninja Developer HS website will link to a URL set by their owners. Be recognized as being part of the Squad, be proud, and get visibility. You might link your profile page, portfolio, Twitter, LinkedIn, etc. URLs are stored off-chain, which means no transaction costs, and the freedom to change your URL at any time.",
  "Priority access to the minting of Warriors NFTs. There will be 2048 of which 1024 will be reserved to Ninja keyword holders.",
  "Access to restricted Discord channels, collaborations with other collections, and exclusive Web3 projects deals."
];

export const sourceCodeList: string[] = [
  "The React.js code for this website, which supports multiple configurations and modes (eg: test/production for pre-sale, sale, post-sale, etc.), connecting with MetaMask and WalletConnect, whitelist checking, filterable keyword listing and utilities (eg: a tool to take a snapshot of the tokens ownership for any ERC-721 contract).",
  "The Node.js backend code that verifies the NFT ownership and manages the associated url(s) on a database.",
  "The C# / .NET Core tools to generate the keyword-images with random styles, shuffle their order, and generate the corresponding metadata files."
];

export type QuestionAnswersType = {
  question: string;
  subText: string;
  answers?: string[];
};

export const questionAndAnswer: QuestionAnswersType[] = [
  {
    question: "Who are ninja developers?",
    subText:
      "If you are one of us, you should know already(*). But, just to make it clear, you're one if:",
    answers: [
      "You don't need a debugger, the debugger needs you.",
      "You smash your tasks by 11am, so that you can spend the rest of your day on Twitter and Reddit.",
      "You have FAANG (MANGA now?) knocking at your door praying you to join them, skipping the interview process.",
      "You are underpaid for what you do, but you don't care because you are a crypto OG.",
      "You have a maxed out MBP and a $2k ergonomic chair.",
      "You dodge stupid work questions on Slack by replying with the perfect GIF."
    ]
  },
  {
    question: "Ok, but are you really that badass?",
    subText: "You judge for yourself:",
    answers: [
      "Our resume lists the things we haven't done, it's shorter that way.",
      "Our IDE doesn't do code analysis, it does code appreciation.",
      "We compile and run our code before submitting, but only to check for compiler and CPU bugs.",
      "We can instantiate abstract classes.",
      'When we say "Hello World", the world says "Hello Ninjas".',
      "You don't explain your work to us, we explain your work to you.",
      "We don't write bugs, just features you can't understand.",
      "Chuck Norris is our 20% project. We completed it in 10%."
    ]
  },
  {
    question: "Where can I get Ninja NFTs and be part of the Squad?",
    subText:
      "Our exclusive 1024 NFTs will be released sometime in March 2022. Follow us on Twitter and join the free Ninja Developer Discord to stay tuned."
  },
  {
    question: "What wallet should I use?",
    subText:
      "If you don't know what MetaMask and WalletConnect are and how to use them, all this is probably not for you."
  },
  {
    question: "Are there benefits to holding multiple Ninja keywords?",
    subText:
      "Yes, you will be able to mint 1 Warrior NFT for each keyword you hold."
  },
  {
    question: "What blockchain are you on?",
    subText:
      "Ethereum, because of its reliability and ease of use (in comparison to alternatives at least)."
  },
  {
    question: "Why do I need a keyword?",
    subText:
      "You don't. If you're not a ninja developer. If you are, you definitely want to be part of our Squad(*)."
  },
  {
    question:
      "No keywords for {languageX}? Why?! It can't get any ninja-er than that...",
    subText:
      "We feel you...but a supply of 1024 was the perfect number, as you'll surely agree, and it couldn't fit all languages. And anyway, tbh, all relevant languages worth knowing today should be present :P(*)."
  }
];

export type RoadMapListType = {
  title: string;
  steps: string[];
};

export const roadMapList: RoadMapListType[] = [
  {
    title: "V 0.9: HELLO WORLD",
    steps: [
      "Ninja website launched.",
      "Discord and Twitter channels are now open and starting to attract the real OGs.",
      "Call to all Web2 and Web3 Ninjas.",
      "Requirements for initial whitelist slots to be provided into the Discord's #announcement channel."
    ]
  },
  {
    title: "V 1.0: PRODUCTION",
    steps: [
      "1st NFT drop of 1024 unique Ninja keywords: ERC-721 Smart Contract on Ethereum and IPFS for decentralized storage.",
      "Blind minting for whitelisted users during pre-sale, followed by public sale and reveal.",
      "The collection will have 8 LEGENDARY keywords and 32 ultra-rare. Good luck to all!",
      "Keep up on our Discord's #announcement channel for the details about whitelists, pre-sale, and public sale."
    ]
  },
  {
    title: "V 1.1: BENEFITS GO LIVE",
    steps: [
      "Get all the source code powering this website's frontend + backend, and other internal tools used for the drop. More details are in the Token Utility section above.",
      "Access to private Discord channels will be unlocked using collab.land.",
      "Recognition on the Ninja Developer's Hall of Fame Gallery: link your profile or website from the iconic keyword you own (link details are stored off-chain, and you'll be able to update this at any time and at no cost)."
    ]
  },
  {
    title: "V 2.0: WARRIORS",
    steps: [
      "2nd drop of 2048 new unique Warrior NFTs, of which 1024 will be reserved to Ninja holders!",
      "Mint price, whitelist requirements, and other details will be voted on and decided by the Ninja holders community."
    ]
  },
  {
    title: "V 2.1: ONWARDS AND UPWARDS",
    steps: [
      "NSquad masters might introduce Web3 and NFT projects to which Ninja and Warrior Developers could apply on a full-time or part-time basis.",
      "DNinjas and Warriors work together to take control of the community and creation of new initiatives."
    ]
  }
];
